[project]
name = "exttorch"
version = "0.0.1"
authors = [
  { name="denis-spe", email="denisbrian07@gmail.com" },
]
description = "A torch sequential extension with hyperparameter tuner for Python"
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"